### ISSUE TITLE
Bug: Out of bounds explored tiles

### ISSUE THREAD

**Issue by dkonar** [Realmz-Castle/Realmz-Remake#15]
Reproduced in sd mode on the dev branch.

When you walk to a certain place on the map the game crashing because explored tiles is out of bounds.

<img width="1213" alt="Screen Shot 2024-07-13 at 3 29 39 PM" src="https://github.com/user-attachments/assets/1182dad4-bfc8-4877-b173-fb8aa9062d2a">

**Comment by daerogami** [comment]
I had applied the fix Samuel mentioned in Discord and never created a PR, I must've done it right before I had to step away. I haven't even tested it yet.
